tap "homebrew/cask-drivers"
# package with no sha signature
cask "logitech-options"
cask "google-cloud-sdk"
# enforce sha signature for the following packages
cask_args require_sha: true
# terminal
cask "iterm2"
brew "fish"
# languages
brew "go"
brew "python"
# dev tools
# only install vscode if not already installed (as it auto-updates itself)
cask "visual-studio-code" unless system "test -f /usr/local/bin/code"
brew "gnupg"
cask "gpg-suite"
brew "kubectl" unless system "test -f /usr/local/bin/kubectl"
brew "helm" unless system "test -f /usr/local/bin/helm"
brew "azure-cli"
brew "awscli"
cask "postman"
